### ISSUE TITLE
Jump to timeline

### ISSUE THREAD

**Issue by scienceworld** [ScienceWorldCA/domelights#11]
The timeline should be able to jump to the box you click on. It’s annoying to have to wait until the timeline comes back to the frame you want to edit.

![image](https://cloud.githubusercontent.com/assets/3997916/6494982/ca2c65ee-c27a-11e4-9c88-58d86453a163.png)

**Comment by RobertButterworth** [comment]
Timeline Jumping added

**Comment by scienceworld** [comment]
would you want to create a new "alpha release v0.2.2" in git and do whatever it takes to push your change into the branch that our server auto updates to?

**Comment by RobertButterworth** [comment]
Updated to v0.2.2

**Comment by scienceworld** [comment]
Rob, where is the commit for the timeline jumping?  we are updated to v0.2.2 and no timeline jumping seems to be there.

**Comment by scienceworld** [comment]
my bad.  it's there and I found the commit.  I had to flush the cash to get the updated javascript.

5bb91b7c14495334d56ec00cd1b19cf5c9811fe9
