### ISSUE TITLE
Naming/Terminology

### ISSUE THREAD

**Issue by jporterscienceworld** [ScienceWorldCA/domelights#28]
What's the difference between a "pattern" and a "video"?

**Comment by scienceworld** [comment]
I think its more of a back end process.  Patterns are mathematically calculated formulas for updating lights, and videos are well, videos that trigger lights to match the video thats playing in the background.

to a user, though, there wont be much of a different.  it's still a base pattern.

**Comment by RobertButterworth** [comment]
Actually, everything but the patter and video are mathematically created. Patterns are static images, I disabled the option to to scroll the image around the dome but when it's fixed I will put it back. Maybe..

Change Pattern to Decal or Image? and Video can stay is?

**Comment by jporterscienceworld** [comment]
Ah, that makes more sense . . . I'd say "Pattern" works then. Maybe "Animation" or "Motion" instead of Video. Video makes me think I'll be able to upload a YouTube video of a Cat playing a piano onto it.

**Comment by RobertButterworth** [comment]
Agreed.

**Comment by RobertButterworth** [comment]
Renamed
