### ISSUE TITLE
Need Streaming media server with CORS solution for Animation Brushes

### ISSUE THREAD

**Issue by RobertButterworth** [ScienceWorldCA/domelights#39]
To get animation brushes to work, the video asset needs to be located on a streaming media server with CORS (http://en.wikipedia.org/wiki/Cross-origin_resource_sharing). The animation brush requests a certain time from the video and pulls the information from the video frame to display on the dome, a normal server will not allow for this to happen.

Currently I am hosting the video files on my dropbox account.

**Comment by TyIsI** [comment]
This shouldn't be an issue, as the video content would be fetched from the same webserver as the front-end interface is server from.
